### PR TITLE
new build process, new packages: `@tabler/icons-react`, `@tabler/icons-preact`, `@tabler/icons-svelte`, `@tabler/icons-vue`, `@tabler/icons-solidjs`, `@tabler/icons-png`, `@tabler/icons-pdf`, `@tabler/icons-eps`

### LINKED ISSUE #359: Support Tree Shaking / Modularized Imports (React)
Currently, the React build produces a single `index.cjs.js` / `index.esm.js` file including all icons. This is fine for some use cases but can cause bundle bloat / dev server slowness. It would be awesome if each icon was additionally put in its own file so they can be tree shaken effectively by a bundler. This would also allow something like Next.js to use  the [`modularizeImports` feature](https://nextjs.org/docs/advanced-features/compiler#modularize-imports) to not bundle every single icon in both the development and production build.

Example:
```json
"@tabler/icons": {
  "transform": "@tabler/icons/{{member}}"
}
```

### PR DESCRIPTION
**Pull request by codecalm**
resolves #359, #366

### CODE REVIEW

**Comment by m1911star** [comment]
Is there any update about this pull request?

**Comment by codecalm** [comment]
@m1911star I must test it all firstly :)

**Comment by itzTheMeow** [comment]
another status update? looking forward to this!

**Comment by kamishirorui** [comment]
+1 on this! would reduce our bundle size massively

**Review by LoiLock — APPROVED** [review]

**Review by XLordalX — APPROVED** [review]

**Comment by LoiLock** [comment]
Looks good to me 👍🏻

**Review by LoiLock — APPROVED** [review]

**Comment by itzTheMeow** [comment]
Have you considered a `fill` property on the icons? The ability to easily change the fill color would be useful for certain icons:
image
image

**Pull request merged**
