### PR TITLE
Fix exports for node (next)

### LINKED ISSUE #126: Error using Nextjs
image

image

### PR DESCRIPTION
**Pull request by FreexD**
Closes #126

### CODE REVIEW

**Review by LitoMore — APPROVED** [review]

**Review by ramon-villain — APPROVED** [review]

**Review by SBoudrias — APPROVED** [review]

**Comment by SBoudrias** [comment]
We tested this fix on our Next.js app, and it worked great afterwards :+1:

Thanks @FreexD

**Comment by SBoudrias** [comment]
Hey @FreexD, what are your plans for pushing a new release on npm?

**Comment by FreexD** [comment]
@SBoudrias will do our best to publish some more icons with it with a minor upgrade this week. If we can't make it, I'll probably publish it in a patch on the weekend :)

**Comment by FreexD** [comment]
@SBoudrias published in `1.41.2` patch :)

**Pull request merged**
