### PR TITLE
Generate dynamic imports for icons-react

### LINKED ISSUE #998: Get Icon dynamically
Is there a way to import the Icon dynamically in React? For example: 

> \<Icon name={iconName} />

### PR DESCRIPTION
**Pull request by timheerwagen**
fixes #998

This PR generates a dynamic import for every Icon, so it can be used for lazy loading.

Also i had to use `slash` when building, because Windows could not read the joined path.

### CODE REVIEW

**Comment by kismusito** [comment]
Any update about this?

**Comment by timheerwagen** [comment]
Will this PR be merged, or should I make some changes?

**Comment by devcshort** [comment]
I _**NEED**_ this for my current project. Please merge it whoever needs to :'(

**Comment by timheerwagen** [comment]
Still interested in this feature.

**Comment by aminelemaizi** [comment]
I would love yo have this feature, any chance to integrate this in the next release?

**Comment by gDlugokecki** [comment]
Is there a chance somebody could merge this? This is valuable and highly desired!

**Comment by codecalm** [comment]
thank you for your help! ❤️

**Comment by KevinVandy** [comment]
Since this is now crashing people's machines in development mode, can this PR be reversed? It's not fun having people yell at me every day that this package breaks there dev server just because I recommended it as a peerDep.

**Comment by nicosammito** [comment]
> Since this is now crashing people's machines in development mode, can this PR be reversed? It's not fun having people yell at me every day that this package breaks there dev server just because I recommended it as a peerDep.

Would be a good idea to reverse this, because we have problems too

**Pull request merged**
