### PR TITLE
Add icons 'label' (filled & outline) & 'folder-upload' (outline)

### PR DESCRIPTION
**Pull request by CHE1RON**
image

We needed a label variant (that was distinct enough from `badge` and `tag`) and also `folder-plus` was more like "create folder" than "upload folder", so here goes .. if there are any changes to be made, I'll happily do it, and feedback is always welcome.

Cheers 🍒 

**Changelog**: 
2024-06-29: open PR with `label` (both outlined & filled) and `folder-upload`
2024-07-01: make filled `label` same length as `outline` variant 
2024-07-03: add `label-off` icon (outline)

### CODE REVIEW

**Comment by CHE1RON** [comment]
// Update: Right, I think I have to add some metadata, right? Is there any resource on what to include in there, like unicode or something? Though I guess that does not have to be present, right .. ?

**Comment by codecalm** [comment]
we have icon for folder upload 🙂 

folder-up

**Comment by codecalm** [comment]
I've merged other icons, thank you for help!

**Comment by CHE1RON** [comment]
You're welcome! Maybe we could keep it as alternate version or so .. ? We like that it directly corresponds to file upload, which also comes with an arrow in the middle 😉

**Pull request merged**
