### PR TITLE
Filled version of icons

### LINKED ISSUE #22: Filled Variations
Multiple Strokes feature is awesome. My suggestion is to also add a filled icon option, to cover a wider range of usages.
Examples taken from [Ionic](https://ionicons.com/)
Screenshot from 2020-05-14 19-21-48Screenshot from 2020-05-14 19-21-53

### PR DESCRIPTION
**Pull request by codecalm**
First attempt to create a filled-in version of the icons. Simple and most commonly used shapes will be filled in first. 

Xnapper-2022-10-28-03 55 21

closes #22 #63

### CODE REVIEW

**Comment by martinrademacher** [comment]
Will this PR be part of one off the next releases? I'm really looking forward to it. thank you.

**Comment by codecalm** [comment]
yes, probably those icons will be released with 1.112 or 1.113 :)

**Comment by Nzent** [comment]
Beautiful 🥰 Useful 🤗

**Comment by Lepidopteran** [comment]
Any updates on this? This would be useful to have.

**Comment by martinrademacher** [comment]
Hey, this PR was moved to v2. Will this be released soon? Can we help to make this happen? I'm obviously not the only one waiting for the filled icons. I would really appreciate the option.

**Pull request merged**
