### PR TITLE
Add zoom out and question icons

### PR DESCRIPTION
**Pull request by mjchang**
Resolve https://github.com/tabler/tabler-icons/issues/147

### CODE REVIEW

**Review by adderpositive — COMMENTED** [review]
Works well!

**Comment by mjchang** [comment]
@codecalm bump on this

**Comment by mjchang** [comment]
@codecalm Bump again

**Comment by codecalm** [comment]
@mjchang `icons-react/index.d.ts` and `icons-react/index.js` are generated automatically. If we merge this PR with next release the problem will return. I must find why this icons are not generated properly.

**Comment by codecalm** [comment]
I've made fix in a9e01fc2eb9e83c581e9e668dc822a31d0c1f632, so from now all icons will be generated properly :)

**Pull request closed without merging**
