### PR TITLE
fix name of `device-game-pad.svg` to `device-gamepad-3.svg`

### LINKED ISSUE #799: File conflict for `device-game-pad.svg` and `device-gamepad.svg`
Since release `2.32.0`, svelte won't build with `icons-svelte` anymore. The problem boils down to the newly introduced `device-game-pad.svg` icon. It causes a file conflict, so that only `IconDeviceGamePad.svelte` is in the release, but not `IconDeviceGamepad.svelte`. The latter, however, is still referenced in the built `tabler-icons-svelte.js` file, causing the svelte build to fail when using `2.32.0`.

Suggestion: As there already are two gamepad icons, change the latest added one to be `device-gamepad-3.svg`. I will open a PR for that.

### PR DESCRIPTION
**Pull request by knulpi**
fixes #799

### CODE REVIEW

**Comment by hanszoons** [comment]
Also fixes #810, #826 and #838

**Comment by miguelgargallo** [comment]
I solved using

`"@tabler/icons-svelte": "2.30.0",`

**Comment by gabrielnvian** [comment]
Any timeline on this?

**Comment by codecalm** [comment]
merged, thank you for your help! 🙂

**Pull request merged**
