### PR TITLE
Rename albolia -> algolia

### PR DESCRIPTION
**Pull request by Narcha**
Unless this is intentional, the "Albolia" icon is probably supposed to be called [Algolia](https://www.algolia.com/).

### CODE REVIEW

**Comment by codecalm** [comment]
@Narcha can you create PR with only renamed file `src/_icons/albolia.svg` ?

**Comment by Narcha** [comment]
Sure. But why is this preferable to the current approach?

**Comment by Narcha** [comment]
Created #317

**Comment by Narcha** [comment]
Closing since #317 was merged

**Comment by codecalm** [comment]
> Sure. But why is this preferable to the current approach?

all files that you renamed are automatically generated from `src/_icons`, and if you don't change source, all files will be replaced to old value with next release :)

**Comment by codecalm** [comment]
I'm closing this release, thank you for your help :)

**Comment by Narcha** [comment]
I see. Thank you for your work and for merging!

**Pull request closed without merging**
