### PR TITLE
Version 2.0!

### PR DESCRIPTION
**Pull request by codecalm**
### 9 New packages

The latest release includes 8 new packages so you can always have the latest versions of icons in your favorite framework:

- `@tabler/icons-react`
- `@tabler/icons-preact`
- `@tabler/icons-svelte`
- `@tabler/icons-vue`
- `@tabler/icons-solidjs`
- `@tabler/icons-png`
- `@tabler/icons-pdf`
- `@tabler/icons-eps`
- `@tabler/icons-webfont`

### Filled version of icons

First part of filled version of icons. Almost 100 icons has filled variant.

### Optimized paths

All icons has merged all paths to a single one wherever possible.

### CODE REVIEW

**Comment by LoiLock** [comment]
Currently, this reliably adds over 100kb to our final bundle. Using @tabler/icons-react

v2:
image

Previous (v1.119 I believe):
image

**Comment by codecalm** [comment]
@LoiLock can you try `2.0.0-alpha2`? :) should be better

**Comment by LoiLock** [comment]
@codecalm Thanks! That seems to have fixed it

**Comment by y-kalka** [comment]
@codecalm  Thanks for the huge update.

Unfortunately i am getting the following error when i try to import the icons into a sveltekit project
```
Failed to load url ./defaultAttributes (resolved id: ./defaultAttributes). Does the file exist?
```
I am importing the icons like this
```svelte
<script lang="ts">
    import { IconMail } from '@tabler/icons-svelte';
</script>

<IconMail />
```

**Comment by itzTheMeow** [comment]
Seeming to also have an issue with the svelte package:

```
✘ [ERROR] Could not resolve "@tabler/icons-svelte"

    src/routes/branding/ColorSwatch.svelte:22:32:
      22 │ ..."@tabler/ic...
         ╵    ~~~~~~~~~~~

  You can mark the path
  "@tabler/icons-svelte" as
  external to exclude it
  from the bundle, which
  will remove this error.
```

I'm using esbuild-svelte to build the project.

Here's the ColorSwatch.svelte file:
image

and my esbuild configuration:
```js
import useAutoprefixer from "autoprefixer";
import esbuild from "esbuild";
import postCssPlugin from "esbuild-style-plugin";
import esbuildSvelte from "esbuild-svelte";
import fs from "fs";
import sveltePreprocess from "svelte-preprocess";
import useTailwind from "tailwindcss";

console.log("Building client...");
esbuild
  .build({
    entryPoints: [`./src/index.ts`],
    bundle: true,
    outdir: `./dist`,
    mainFields: ["svelte", "browser", "module", "main"],
    minify: false,
    sourcemap: "inline",
    splitting: true,
    write: true,
    format: `esm`,
    alias: { path: "path-browserify" },
    external: ["fs"],
    watch: process.argv.includes(`--watch`),
    plugins: [
      esbuildSvelte({
        filterWarnings: (w) => !w.code.startsWith("a11y-"),
        preprocess: sveltePreprocess(),
      }),
      postCssPlugin({
        postcss: {
          plugins: [useTailwind, useAutoprefixer],
        },
      }),
    ],
    logLevel: "info",
    target: "es6",
    loader: { ".png": "file" },
  })
```

**Comment by itzTheMeow** [comment]
seems to have fixed the previous issue, however fill colors don't seem to work. (icons-svelte)

image

image

neither do classes or other props

image


image

**Pull request merged**
