### PR TITLE
Amazon icon

### PR DESCRIPTION
**Pull request by synapt**
Introduces the amazon icon to the list, assuming I understood the unicode referencing appropriately I assigned it the next available incremental value of `f1df`. 

Relative to request #136

### CODE REVIEW

**Comment by codecalm** [comment]
sorry, but this icon does not fit stylistically into the whole package

**Comment by synapt** [comment]
"Stylistically"?  You literally have tons of other brands icons in the package.  Could you perhaps clarify and I could correct (though I don't know to what extent since the amazon icon is, well, the amazon icon).

**Comment by codecalm** [comment]
@synapt can you see the difference? :)

Screenshot 2022-06-26 at 23 22 50

**Comment by synapt** [comment]
So then just make it a hollow A with a similar stroke thickness?  You could have just said that and I could have updated this PR lol.

**Pull request closed without merging**
